<div class="sitemaphtml-data">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Categories') ?></h2>
        <?php foreach( $this->getCategories() as $_category):  ?>
            <?php 
//                  var_dump($_category->getData()); 
//                  exit();
                  $marginvalue = 40 * ($_category['level']-2);
            ?>
            <a style="margin-left:<?php echo $marginvalue;?>px;" href="<?php echo $_category->getUrl(); ?>">  <?php echo $_category->getName();?></a> <br/>    
        <?php endforeach; ?>
    </div>
</div>

<?php 

//$rootcatId= Mage::app()->getStore()->getRootCategoryId();
//$categories = Mage::getModel('catalog/category')->getCategories($rootcatId);
//function  get_categories($categories) {
//    $array= '<ul>';
//    foreach($categories as $category) {
//        $cat = Mage::getModel('catalog/category')->load($category->getId());
//        $marginvalue = 40 * ($category['level']-2);
//        $count = $cat->getProductCount();
//        $array .= '<li>'.
//        '<a style="margin-left:'.$marginvalue.'px;" href="' . Mage::getUrl($cat->getUrlPath()). '">' .
//                  $category->getName() . "(".$count.")</a>\n";
//        if($category->hasChildren()) {
//            $children = Mage::getModel('catalog/category')->getCategories($category->getId());
//             $array .=  get_categories($children);
//            }
//         $array .= '</li>';
//    }
//    return  $array . '</ul>';
//}
//echo  get_categories($categories); 

?>
