<!--
<?php var_dump(Mage::getStoreConfig('sitemap/frontend/page')); ?>
<?php var_dump(Mage::getStoreConfig('sitemap/frontend/category')); ?>
<?php var_dump(Mage::getStoreConfig('sitemap/frontend/product')); ?>
-->

<div class="sitemaphtml-navigation"> 
    <a href="<?php echo $this->getUrl('sitemaphtml/index/index') ?>" title="<?php echo $this->__('Sitemap index') ?>"> <?php echo $this->__('Sitemap index') ?></a>
    <?php if (Mage::getStoreConfig('sitemap/frontend/category')): ?>
        <a href="<?php echo $this->getUrl('sitemaphtml/index/category') ?>" title="<?php echo $this->__('Sitemap categories') ?>"> <?php echo $this->__('Categories') ?></a>
    <?php endif;?>
    <?php if (Mage::getStoreConfig('sitemap/frontend/product')): ?>
        <a href="<?php echo $this->getUrl('sitemaphtml/index/product') ?>" title="<?php echo $this->__('Sitemap products') ?>"> <?php echo $this->__('Products') ?></a>
    <?php endif;?>
    <?php if (Mage::getStoreConfig('sitemap/frontend/page')): ?>
        <a href="<?php echo $this->getUrl('sitemaphtml/index/page') ?>" title="<?php echo $this->__('Sitemap pages') ?>"> <?php echo $this->__('Pages') ?></a>
    <?php endif;?>    
</div>